version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:23007
    volumes:
      - .:/app
    ports:
      - "23007:23007"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://ansade_user:ansade_password@db:5432/ansade_db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ansade_db
      - POSTGRES_USER=ansade_user
      - POSTGRES_PASSWORD=ansade_password
    ports:
      - "24007:5432"

volumes:
  postgres_data:

